# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Practical-Deep-Learning-for-Coders-Lesson1',
                'doc_host': 'https://danrosher.github.io',
                'git_url': 'https://github.com/danrosher/Practical-Deep-Learning-for-Coders-Lesson1',
                'lib_path': 'Practical_Deep_Learning_for_Coders_Lesson1'},
  'syms': { 'Practical_Deep_Learning_for_Coders_Lesson1.core': { 'Practical_Deep_Learning_for_Coders_Lesson1.core.foo': ( 'core.html#foo',
                                                                                                                          'Practical_Deep_Learning_for_Coders_Lesson1/core.py')}}}
